In [2]:
import numpy as np;
import pandas as pd;
import matplotlib.pyplot as plt


In [ ]:
a = np.array([1,2,3]);
b = np.array([1,3,4]);
kh = (a+b);
kh

array([2, 5, 7])

In [6]:
print(a.shape);
print(b.shape);

(3,)
(3,)


In [13]:
a = np.array([1,2,3,4,5,6,7,8,9]);
b = np.array([1,2,3,4,5,6,7,8,9]);
k = np.concatenate((a,b));
k

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9]);
b = a[2:7];
b

array([3, 4, 5, 6, 7])

In [16]:
sum = np.sum(a);
sum

np.int64(45)

In [17]:
sum = np.max(a);
sum

np.int64(9)

In [21]:
sum = np.min(a);
sum

np.int64(1)

In [ ]:
a = np.array([22,33,44,55]);
b = np.array([11,77,88,99]);
c = a+b;


array([ 33, 110, 132, 154])

In [26]:
a = np.random.rand(10,15,20);
a

array([[[0.47160683, 0.30281391, 0.91049469, ..., 0.10456362,
         0.0420297 , 0.51645723],
        [0.91907348, 0.97264914, 0.522375  , ..., 0.62976084,
         0.60193014, 0.75885772],
        [0.67449084, 0.01664837, 0.56830224, ..., 0.27800281,
         0.12545256, 0.72354909],
        ...,
        [0.09334053, 0.5891102 , 0.76203064, ..., 0.70931057,
         0.74134565, 0.8585943 ],
        [0.76136975, 0.65953055, 0.79090266, ..., 0.22723716,
         0.95777536, 0.33361764],
        [0.34498495, 0.83501213, 0.39293407, ..., 0.55439637,
         0.40003771, 0.55293731]],

       [[0.8706226 , 0.99566701, 0.83721909, ..., 0.91017655,
         0.27337475, 0.73843832],
        [0.99028517, 0.61252011, 0.64934387, ..., 0.25773868,
         0.85261201, 0.74295796],
        [0.48361947, 0.46503926, 0.96068953, ..., 0.95737119,
         0.92791794, 0.95725462],
        ...,
        [0.13318276, 0.70774216, 0.21603223, ..., 0.57859627,
         0.54645638, 0.22135962],
        [0.7

In [27]:
a = np.array([1,3,5,8]);
b = np.array([2,9,8,5]);
c = np.vstack((a,b));
c

array([[1, 3, 5, 8],
       [2, 9, 8, 5]])

In [28]:
c = np.hstack((a,b));
c

array([1, 3, 5, 8, 2, 9, 8, 5])

In [29]:
c = np.mean(a);
c

np.float64(4.25)

In [30]:
c = np.std(b);
c

np.float64(2.7386127875258306)

In [34]:
data = {
    "Name":["Reza","Ali","Hossein"],
    "Age":[18,10,14],
    "phonenumber":["09922313387","09193485713","09191466985"]
}
h = pd.DataFrame(data);
h

Name  Age  phonenumber
0     Reza   18  09922313387
1      Ali   10  09193485713
2  Hossein   14  09191466985