In [4]:
import numpy as np;
import pandas as pd;
import matplotlib.pyplot as plt


In [5]:
a = np.array([1,2,3]);
b = np.array([1,3,4]);
kh = (a+b);
kh

array([2, 5, 7])

In [6]:
print(a.shape);
print(b.shape);

(3,)
(3,)


In [7]:
a = np.array([1,2,3,4,5,6,7,8,9]);
b = np.array([1,2,3,4,5,6,7,8,9]);
k = np.concatenate((a,b));
k

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
a = np.array([1,2,3,4,5,6,7,8,9]);
b = a[2:7];
b

array([3, 4, 5, 6, 7])

In [9]:
sum = np.sum(a);
sum

np.int64(45)

In [10]:
sum = np.max(a);
sum

np.int64(9)

In [11]:
sum = np.min(a);
sum

np.int64(1)

In [12]:
a = np.array([22,33,44,55]);
b = np.array([11,77,88,99]);
c = a+b;


In [13]:
a = np.random.rand(10,15,20);
a

array([[[6.39628114e-01, 5.17289870e-01, 9.78016445e-01, ...,
         4.21988542e-01, 2.41168076e-01, 1.21309234e-01],
        [7.99350823e-01, 7.92204394e-01, 1.18413481e-01, ...,
         7.97262663e-01, 5.45885288e-01, 4.29087517e-01],
        [7.65634696e-02, 2.50581767e-01, 8.74850994e-01, ...,
         8.43055462e-01, 9.26099369e-01, 7.08782015e-01],
        ...,
        [6.22555246e-01, 2.44886927e-01, 8.04922719e-01, ...,
         5.87224554e-01, 4.59403960e-01, 3.71945158e-02],
        [2.39829697e-01, 7.20528840e-01, 9.38330769e-01, ...,
         3.62693798e-01, 7.18984755e-01, 7.14103842e-01],
        [4.05280015e-01, 1.69635682e-01, 5.31282968e-02, ...,
         9.76649854e-01, 1.75007906e-04, 6.40037507e-02]],

       [[4.17843169e-01, 5.87236265e-01, 6.50753168e-01, ...,
         5.18774598e-01, 5.20369831e-01, 8.54828380e-01],
        [7.21335502e-01, 9.44942956e-01, 9.37637016e-01, ...,
         3.00959947e-01, 9.36626475e-01, 7.22988423e-01],
        [3.18352960e-03, 

In [14]:
a = np.array([1,3,5,8]);
b = np.array([2,9,8,5]);
c = np.vstack((a,b));
c

array([[1, 3, 5, 8],
       [2, 9, 8, 5]])

In [15]:
c = np.hstack((a,b));
c

array([1, 3, 5, 8, 2, 9, 8, 5])

In [16]:
c = np.mean(a);
c

np.float64(4.25)

In [17]:
c = np.std(b);
c

np.float64(2.7386127875258306)

In [18]:
data = {
    "Name":["Reza","Ali","Hossein"],
    "Age":[18,10,14],
    "phonenumber":["09922313387","09193485713","09191466985"]
}
h = pd.DataFrame(data);
h

Name  Age  phonenumber
0     Reza   18  09922313387
1      Ali   10  09193485713
2  Hossein   14  09191466985

In [21]:
df = pd.DataFrame(data);
df

Name  Age  phonenumber
0     Reza   18  09922313387
1      Ali   10  09193485713
2  Hossein   14  09191466985

In [22]:
df.head();
df

Name  Age  phonenumber
0     Reza   18  09922313387
1      Ali   10  09193485713
2  Hossein   14  09191466985

In [23]:
df.describe();
df

Name  Age  phonenumber
0     Reza   18  09922313387
1      Ali   10  09193485713
2  Hossein   14  09191466985

In [24]:
df["Age"];
df

Name  Age  phonenumber
0     Reza   18  09922313387
1      Ali   10  09193485713
2  Hossein   14  09191466985